name: Customies
description: An Altay plugin that implements support for custom blocks, items and entities.

main: customiesdevs\customies\Customies
src-namespace-prefix: customiesdevs\customies
version: 1.5.1
api: 5.44.0

authors:
  - DenielWorld
  - TwistedAsylumMC
contributors:
  - JackNoordhuis
  - Unickorn
  - abimek
